from typing import Any, Generic, TypeVar

T = TypeVar('T')

class State(Generic[T]):
    value: T
    def set(self, v: T) -> None: ...

def state(initial: T) -> State[T]: ...

class ui:
    def div(*args: Any, **kwargs: Any) -> Any: ...
    def h1(*args: Any, **kwargs: Any) -> Any: ...
    def button(*args: Any, **kwargs: Any) -> Any: ...
    def iframe(*args: Any, **kwargs: Any) -> Any: ...


def run(component: Any, host: str | None = None, port: int | None = None) -> None: ...
